# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LCModelObjectExample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LCModelObjectExample
  pod 'AFNetworking', '~> 3.1.0'
  pod 'FMDB', '~> 2.6.2'

  target 'LCModelObjectExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
